### ISSUE TITLE
SEBC Evaluation: Fail

### ISSUE THREAD

**Issue by mfernest** [deyabhishek79/SEBC#16]
I am sorry to say you did not pass the SEBC course. Although the lab work was complete (with a few minor inconsistencies), I marked several challenge stages incomplete for including the wrong information or setup. Please see the Issue notes for further details.

You are however eligible to re-take the exam at no cost, and there is no need to attend the course a second time. If you wish to attempt the exam at a later date, please contact the instructor for details.

**Comment by deyabhishek79** [comment]
@mfernest  - I would like to take the test next week again over the weekend. Please provide me the challenge details and I will try to complete it within a 3 hour slot
